# Datasource
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/filmorate
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.data-source-properties.reWriteBatchedInserts=true
spring.sql.init.mode=always
# Datasource Proxy
logging.level.net.ttddyy.dsproxy.listener=DEBUG
# HTTP logging (Logbook)
logging.level.org.zalando.logbook=TRACE
# Server encoding
server.servlet.encoding.enabled=true
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true